---
title: "Glossary"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    always_allow_html: yes
bibliography: HDX.bib
vignette: >
  %\VignetteIndexEntry{Glossary}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Variables

Variable names are used in the package consequently. Below are definitions of the terms. 

## Time points of measurement

time_t - chosen time point of measurement.

time_0 - minimal exchange control time point of measurement.

time_100 - maximal exchange control time point of measurement.

## Deuterium uptake values

deut_uptake -	deuterium uptake [Da].

err_deut_uptake -	error associated with deuterium uptake [Da].

frac_deut_uptake - fractional deuterium uptake [%].

err_frac_deut_uptake - error associated with fractional deuterium uptake [%].

theo_deut_uptake - theoretical deuterium uptake [Da].

err_theo_deut_uptake - error associated with theoreti.cal deuterium uptake [Da].

theo_frac_deut_uptake - theoretical fractional deuterium uptake [%].

err_theo_frac_deut_uptake - error associated with theoretical fractional deuterium uptake [%].

## Experimental conditions

deut_part - deuterium percentage in solution used in experiment, from range [0, 1].




# Object hdx_data

In the package, the input data is transformed into hdx_data object. The object inherits the data frame properties and has multiple necessary attributes.

## Main data frame

Protein - character, protein name. May have different values.

Start - integer, start position of the peptide in the protein sequence.

End - integer, end position of the peptide in the protein sequence.

Sequence - character, peptide name. 

MaxUptake - numerical, maximal possible uptake value, based on the peptide sequence.

MHP - numerical, monoisotopic mass of the peptide, based on the peptide sequence [Da].

State - character, biological state.

Exposure - numerical, time point of the measurement [min].

File - character, the raw data filename.

z - integer, the charge value.

Inten - numerical, peak intensity.

Center - numerical, geometric centroid value of measured isotopic envelope.


## Attributes

source - character, indicator of the data source (e.g. Dynamx3.0).

has_modification - logical, indicator of the modification presence. The modification information is preserved in the state value.
