tab_input <- tabPanel("Input data",
         br(),
         h4("Upload your file. Otherwise, you will see the example data."),
         h4("Currently HaDeX is limited to `cluster` files from DynamX 3.0 or 2.0 and `tables` file from  HDeXaminer."),
         h4("Accepted file extensions: .csv, .xls, .xlsx. "),
         h4("The supplied file should contain at least two repetitions of the measurement for the uncertainty to be calculated."),
         h4("If the supplied file contains modified peptides, maximal exchange control cannot be applied."),
         #
         fluidRow(
           column(3,
                  fileInput(
                    inputId = "data_file",
                    label = "Choose file:",
                    multiple = FALSE,
                    accept = c(".csv", ".xlsx", ".xls"),
                    placeholder = "No file selected")),
           column(4,
                  h5("File status:"),
                  tags$div(
                    class = "file-status-message",
                    withSpinner(textOutput("data_file_info"))
                  ))
         ),
         #
         h4("Please be aware that loading data (including example file) may take a while. Be patient."),
         h4("For the program to behave correctly, please make sure supplied file fulfills following requirements:"),
         tags$button("Show requirements",
                     class = "collapse-button",
                     style = "width: unset",
                     `data-toggle`="collapse",
                     `data-target`="#reqs"),
         tags$div(
           id = "reqs",
           style = "width: min-content",
           class = "hideable",
           tableOutput("file_req")),
         h3("Settings"),
         h4("Values chosen here are propagated into all of the tables for coherent results."),
         fluidRow(
           column(4,
                  selectInput_h(inputId = "chosen_protein",
                                label = "Choose protein: ",
                                choices = c("db_CD160"),
                                width = "100%"),
                  selectInput_h(inputId = "chosen_control",
                                label = "Choose maximal exchange control for chosen protein: ",
                                choices = c("db_CD160 | CD160 | 1440"),
                                width = "100%"),
                  numericInput_h(inputId = "deut_part",
                                 label = "Choose D20 concentration [%]: ",
                                 value = 90,
                                 min = 0, max = 100, step = 1,
                                 width = "100%"),
                  numericInput_h(inputId = "sequence_start_shift",
                                 label = "Move sequence start:",
                                 value = 1, step = 1,
                                 width = "100%"),
                  numericInput_h(inputId = "sequence_length",
                                 label = "Correct sequence length:",
                                 value = 300, step = 1,
                                 width = "100%"),
                  textOutput("sequence_length_exp_info")
           ),
           column(2,
                  br()),
           column(4,
                  hidden(div(id = "examiner_settings",
                             h3("File from HDeXaminer detected!"),
                             h4("Some of the information from the data file requires your confirmation."),
                             h4("For the additional information on how the data from HDeXaminer is processed, check the requirements above. Keep in mind that the MHP value is generated based on the peptide sequence and therefore, may differ from actual value in case of the modifications."),
                             numericInput_h(inputId = "examiner_fd_timepoint",
                                            label = "FD timepoint [min]:",
                                            value = 1440,
                                            min = 0,
                                            width = "100%"),
                             textInput_h(inputId = "exam_protein_name",
                                         label = "Protein name:",
                                         width = "100%"),
                             textInput_h(inputId = "exam_state_name",
                                         label = "States names:",
                                         width = "100%"),
                             checkboxGroupInput_h(inputId = "exam_confidence",
                                                  label = "Accepted confidence values:",
                                                  choices = c("High", "Medium", "Low"),
                                                  selected = c("Medium", "High")),
                             actionButton(inputId = "exam_apply_changes",
                                          label = "Apply changes to continue"),
                             br(),
                             h5("The calculated values of MPH might slightly differ based on data used and its precision."),
                             a(href="http://www.matrixscience.com/help/aa_help.html", "Used amino mass data"),
                             br(),
                             br(),
                             DT::dataTableOutput("checking_exam_data"),
                             br(),
                             br(),
                             br()
                  ))
           )),
         br(),
         br(),
         br()
)