#' generate_summary_table
#' 
#' @description Generates summary table.
#' 
#' @param dat ...
#' @param confidence_limit_1 ...
#' @param confidence_limit_2 ...
#' @param overlap_distribution_data custom format, generated by
#' \code{\link{generate_overlap_distribution_data}}
#' 
#' @details The format in the table is suggested in Masson, G.R., Burke, J.E., 
#' Ahn, N.G., Anand, G.S., Borchers, C., Brier, S., Bou-Assaf, G.M., Engen, J.R., 
#' Englander, S.W., Faber, J., et al. (2019). Recommendations for performing, 
#' interpreting and reporting hydrogen deuterium exchange mass spectrometry 
#' (HDX-MS) experiments. Nat Methods 16, 595–602
#' 
#' @return ...
#' 
#' @seealso ... 
#' 
#' @export generate_summary_table

generate_summary_table <- function(dat, 
                                   confidence_limit_1,
                                   confidence_limit_2,
                                   overlap_distribution_data){
  
  n_reps <- group_by(dat, Protein, Start, End, Sequence, Modification, State, Exposure) %>%
    summarise(n_rep = length(unique(File))) %>%
    ungroup() %>% 
    pull(n_rep) %>% 
    table() %>% 
    sort(decreasing = TRUE) %>% 
    names() %>% 
    as.numeric()
  
  data.frame(Name = c("HDX time course", 
                      "Number of peptides",
                      "Sequence coverage",
                      "Average peptide length",
                      "Redundancy",
                      "Replicates",
                      #"Average standard deviation",
                      "Significant differences in HDX"), 
             Value = c(length(unique(dat[["Exposure"]])) - 1, # we add control as an additional timepoint 
                       length(unique(dat[["Sequence"]])), 
                       paste0(100*round(mean(overlap_distribution_data[["coverage"]] > 0), 4), "%"), 
                       round(mean(nchar(unique(dat[["Sequence"]]))), 4), 
                       round(mean(overlap_distribution_data[["coverage"]]), 4), 
                       n_reps[1], 
                       #NA, 
                       paste0(confidence_limit_1, " | ", confidence_limit_2))
  )
  
}